### ISSUE TITLE
setion header view can not work with header view of the listview

### ISSUE THREAD

**Issue by ccc-rrr** [bhavyahmehta/ListviewFilter#3]
All the section header views' position are not right when the list view has a header 
view as the index for data starts from 1 not 0, e.g.
aListView.addHeaderView(mListHeader);

And if a header view has been added, how to postion it through the IndexBarView as no data is related to it.

Thanks!

**Comment by bhavyahmehta** [comment]
Hello,

This kind of list view was not designed to use with header.

Thanks & Regards,
Bhavya
